backend:
  name: git-gateway
  repo: Anastasiia-XFR/HUGO
  branch: hugo-netlify-cms-3

# local_backend:
#   url: "http://localhost:8076/api/v1"

media_folder: "/static/images"
public_folder: "/static/images"

# publish_mode: editorial_workflow

logo_url: "/images/favicon.png"
show_preview_links: false 

i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: "en"


collections:

  - label: 'Authors'
    name: 'authors'
    widget: "object"
    folder: 'content/authors'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: 'author-{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: 'author'
    editor:
      preview: false
    sortable_fields: ['date', 'author']
    fields:
      - { name: 'author', label: 'Author Name', widget: string, i18n: true }

  - label: 'Categories'
    name: 'categories'
    widget: "object"
    folder: 'content/categories'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: 'category-{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['date', 'category']
    fields:
      - { name: 'category', label: 'category', widget: string, i18n: true }


  - label: "NEWS"
    name: "news"
    folder: "content"
    path: 'news/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "news-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    filter:
      field: type
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["news"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime",  date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "image", widget: "image", media_folder: "/static/images/news", public_folder: "/images/news", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'categories', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "BETTING"
    name: "betting"
    folder: "content/"
    path: 'betting/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "betting-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["betting"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/betting", public_folder: "/images/betting", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'categories', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
 
  # - label: "Posts"
  #   name: "posts"
  #   folder: "content/"
  #   # path: 'top-news/{{slug}}'
  #   format: 'frontmatter'
  #   create: true
  #   i18n: true
  #   slug: "post-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
  #   identifier_field: 'category'
  #   editor:
  #     preview: false
  #   sortable_fields: ['date', 'author', 'type']
  #   view_groups:
  #     - label: Year
  #       field: date
  #       pattern: \d{4}
  #     - label: Type
  #       field: type
  #     - label: Drafts
  #       field: draft
  #   fields:
  #     - { label: "Title", name: "title", widget: "string", i18n: true }
  #     - { label: "Type", name: "type", widget: "select",  options: ["top-news", "news", "articles", "beginners", "youtube"], required: true, i18n: true }
  #     - { label: "Position", name: "position",  widget: "select",  options: ["top-news-1", "top-news-2", "beginners-top", "news-1", "news-2", "news-3", "news-4", "none"], required: false, i18n: true }
  #     - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
  #     - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
  #     - { label: "Video URL", name: "video", widget: "string", required: false, i18n: true}
  #     - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/top-news", choose_url: true, required: false, i18n: true }
  #     - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
  #     - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
  #     - { label: "Body", name: "body", widget: "markdown", i18n: true }
